[package]
name = "toast-logger-win"
version = "0.5.6"
edition = "2024"
description = "Rust's `log` crate logger that sends logging output to the Windows Toast Notifications."
authors = ["Koji Ishii <kojiishi@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/kojiishi/toast-logger-win"
documentation = "https://docs.rs/toast-logger-win/"
readme = "README.md"
keywords = ["log", "windows", "notifications", "toast"]
exclude = [".github", ".gitignore", ".vscode", "Taskfile.yml"]

[dependencies]
anyhow = "1.0.102"
log = { version = "0.4.30", features = ["std"] }
thiserror = "2.0.18"
winrt-toast = { version = "0.1.1", optional = true }

[dependencies.windows]
version = "0.62.2"
optional = true
features = [
    "Data_Xml_Dom",
    "Foundation",
    "Globalization",
    "UI_Notifications",
]

[features]
default = ["dep:windows"]
# default = ["winrt-toast"]
winrt-toast = ["dep:winrt-toast"]

[package.metadata.docs.rs]
# https://docs.rs/about/metadata
default-target = "x86_64-pc-windows-msvc"
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
