name: Rust Publish

# Controls when the action will run.
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Output rust version for educational purposes
        run: rustup --version

      - uses: actions/checkout@v4

      - name: Publish (crates.io)
        run: cargo publish --verbose
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
